name: Node.js Package

on:
  #   pull_request:
  #     branches:
  #       - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      # skip tests until we add some!
      # - run: npm test

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token_3 }}
          NPM_TOKEN: ${{ secrets.npm_token_3 }}
          GH_TOKEN: ${{ secrets.gh_token }}
#   publish-gpr:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://npm.pkg.github.com/
#           scope: '@jtferns'
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
